### ISSUE TITLE
Low Visibility

### ISSUE THREAD

**Issue by imRohan** [rdarida/pantry-cloud#163]
This project looks great! However, users won't be able to find this project since it's
not linked to from the Pantry homepage/repo.

I propose we add some sort of "client libraries" table to the Pantry homepage and link
to projects just like this!

**Comment by rdarida** [comment]
Hi @imRohan 
It would be good, but firts I have to make some updates on the project.

**Comment by rdarida** [comment]
Hi @imRohan 
I finished the update/refactor on the project.
I welcome any feedback.
Best,
R

**Comment by imRohan** [comment]
Apologies for the slow response. This project looks great, super excited to use this in my own projects. The only suggestion I have is to include some basic usage commands in the README (such as getBasket etc).

The documentation page you've generated [here](https://rdarida.github.io/pantry-cloud/classes/Pantry.html) is great, however, it may help new users to have an example readily available in the README file.

**Comment by rdarida** [comment]
Hi @imRohan,
I updated the README.md as you suggested.

**Comment by imRohan** [comment]
Awesome! Looks great.

Now the next step could be to have a "SDK" page on Pantrys site which lists the available projects.

I'll try working on that from my end.
